/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.gk.workflow.string.reverse

import io.gk.workflow.string.StringActionsWorkerBase
import io.gk.workflow.string.intf.StringReverseWorkflow
import io.gk.workflow.string.reverse.StringReverseWorkflowImpl.Companion.newActivity

class StringReverseWorker : StringActionsWorkerBase() {
    override val implementation: Class<*>
        get() = StringReverseWorkflowImpl::class.java
    override val activityImplementations: Array<Any>
        get() = arrayOf(newActivity())
    override val workflowVersion: String
        get() = "0.1.2"
    override val queueName: String
        get() = StringReverseWorkflow.Q_NAME
}
