apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse
  template:
    metadata:
      labels:
        app: reverse
    spec:
      containers:
      - name: reverse
        image: gireeshkumarg/reverse
        env:
          - name: TEMPORAL_SERVER
            value: temporaltest-frontend:7233
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
