/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.gk.workflow.string.actionswf

import io.gk.workflow.string.WorkerBase

class StringWorkflowWorker : WorkerBase() {
    override val queueName: String
        get() = "string-action-q"
    override val implementation: Class<*>
        get() = StringActionsWorkflowImpl::class.java
    override val workflowVersion: String
        get() = "0.1.2"
}
