/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.2.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    kotlin("jvm") version "1.8.22"
    kotlin("plugin.allopen") version "1.8.22"
    id("java-library")
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("com.google.guava:guava:31.1-jre")
    implementation("io.temporal:temporal-sdk:1.18.2")
    implementation("io.quarkiverse.microprofile:quarkus-microprofile:3.0.0.Final")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_17.toString()
    kotlinOptions.javaParameters = true
}

/**
 * copy libs to other projects mainly to make it easy to copy in image with Dockerfile 
 */
val destinations = listOf("../kebab/libs", "../stringactions-wf/libs", "../reverse/libs","../uppercase/libs", "../wf_client/libs")

destinations.forEachIndexed { index, destination ->
    val taskName = "copyJarTo${index}"

    tasks.register(taskName, Copy::class) {
        dependsOn("jar")
        from(tasks.jar.get().archiveFile.get().asFile)
        into(destination)
    }

    tasks.named("build") {
        finalizedBy(taskName)
    }
}