/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.gk.workflow.string.upper

import io.gk.workflow.string.StringActionsWorkerBase
import io.gk.workflow.string.intf.StringUpperCaseWorkflow

class StringUpperWorker : StringActionsWorkerBase() {
    override val implementation: Class<*>
        get() = StringCapsWorkflowImpl::class.java
    override val workflowVersion: String
        get() = "0.1.2"
    override val queueName: String
        get() = StringUpperCaseWorkflow.Q_NAME
}
