apiVersion: apps/v1
kind: Deployment
metadata:
  name: stringactions-wf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stringactions-wf
  template:
    metadata:
      labels:
        app: stringactions-wf
    spec:
      containers:
      - name: stringactions-wf
        image: gireeshkumarg/stringactions-wf
        env:
          - name: TEMPORAL_SERVER
            value: temporaltest-frontend:7233
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
